### ISSUE TITLE
Can't use the resize button in Mac OSX

### ISSUE THREAD

**Issue by pesky-wobbit** [Cardagon/popout-resizer#4]
After installing the module, I see the button in the lower right of pop out windows but I can't interact with it. Tried left drag, right drag, left click, right click. No effect. My OSX version is 10.14. By the way, changing the default size works.

**Comment by Cardagon** [comment]
Thanks for bringing this up. Few questions:

1) Is this when you run foundry locally? Or in a browser (Chrome/Firefox), if its a browser which one are you using?

2) If you open up a character sheet are you able to resizw that?

**Comment by pesky-wobbit** [comment]
1. I just tested it in foundry stand-alone, in Chrome, and in Firefox.
Doesn't work.
2. In all 3, it doesn't work in character sheets, either.

I am supposed to left-click and drag this control, right?:
[image: image.png]

**Comment by Cardagon** [comment]
I am tempted to think this may be a Foundry Issue, instead of an issue with the module. If you are unable to resize the Character sheet that would imply there is something go wrong with the Foundry Core itself, I would recommend bringing it up in the Foundry Discord.

I did test the module on a Mac OS 10.15 I believe, and it seemed to work properly. 

I will investigate either way, but I would recommend asking the troubleshooting in discord regarding the character sheet re-sizing issue.

(My module uses the exact same re-sizer so if it doesn't work for character sheets it won't work anywhere else either).

**Comment by Cardagon** [comment]
Closing due to no further response.
